### ISSUE TITLE
incorrect offset on capri even numbered selections

### ISSUE THREAD

**Issue by RR7** [Piker-Alpha/AppleIntelFramebufferAzul.sh#1]
when running this on capri, choosing even numbered selection from the options (i.e choosing 2, 4, 6, 8, 10 or 12) picks the incorrect offset and the report is then bad:

here is 4 as an example:

![caprioffset](https://cloud.githubusercontent.com/assets/5463195/4126278/23eeedf2-32ea-11e4-9e40-500db726673c.jpg)

**Comment by Piker-Alpha** [comment]
I know. Already fixed in my local tree. Problem is that too much has changed so you have to wait for the next update or try this:

function _getOffset()
{
  local found=0

  _getDataSegmentOffset
  #
  # Not used: too slow without nm.
  #
  # _getConnectorTableOffset
  platformIDString="${id:8:2}${id:6:2} ${id:4:2}${id:2:2}"

  _DEBUG_PRINT "platformIDString: $platformIDString\n"

  matchingData=$(xxd -s +$dataSegmentOffset -l $dataSegmentLength "$TARGET_FILE" | grep "$platformIDString" | tr -d ':')
  #
  # Not used: too slow without nm.
  #
  # matchingData=$(xxd -s $connectorTableOffset -l 4096 "$TARGET_FILE" | grep "$platformIDString" | tr -d ':')

  data=($matchingData);
  let found=0
  let fileOffset="0x${data[0]}"

  if [[ $gScriptName ~= 'Capri' && "$platformIDString" == "${data[5]} ${data[6]}" ]];
    then
      let fileOffset+=8;
      let found=1
  fi

  if [[ found || "$platformIDString" == "${data[1]} ${data[2]}" ]];
    then
      printf "AAPL,ig-platform-id: $id ("
      printf "$(_printInfo ${id:2:4})"
      printf ") found @ 0x%x/$fileOffset\n" $fileOffset
      #
      # Done.
      #
      return;
  fi

  _PRINT_ERROR "AAPL,ig-platform-id: $id NOT found!\n\n"
  #
  # Show list with platform IDs.
  #
  _showPlatformIDs
}

**Comment by Piker-Alpha** [comment]
This issue should be resolved with a later update. Please try v3.0 Beta.
